// src/common/constants/error-codes.ts

export const ErrorCodes = {
  /* =========================
     GENERAL / SYSTEM
  ========================== */
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',

  /* =========================
     VALIDATION
  ========================== */
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INVALID_ID: 'INVALID_ID',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  INVALID_RATE: 'INVALID_RATE',
  INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',

  /* =========================
     AUTH / SECURITY
  ========================== */
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_ROLE_NOT_ALLOWED: 'AUTH_ROLE_NOT_ALLOWED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',

  /* =========================
     USER
  ========================== */
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_DISABLED: 'USER_DISABLED',
  USER_EMAIL_ALREADY_VERIFIED: 'USER_EMAIL_ALREADY_VERIFIED',
  USER_PROFILE_INCOMPLETE: 'USER_PROFILE_INCOMPLETE',

  /* =========================
     WALLET
  ========================== */
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
  WALLET_LOCKED: 'WALLET_LOCKED',
  WALLET_SUSPENDED: 'WALLET_SUSPENDED',
  WALLET_INACTIVE: 'WALLET_INACTIVE',
  WALLET_BALANCE_NOT_FOUND: 'WALLET_BALANCE_NOT_FOUND',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_NEGATIVE_BALANCE: 'WALLET_NEGATIVE_BALANCE',
  WALLET_CURRENCY_NOT_SUPPORTED: 'WALLET_CURRENCY_NOT_SUPPORTED',

  /* =========================
     TRANSACTIONS
  ========================== */
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  TRANSACTION_PENDING: 'TRANSACTION_PENDING',
  TRANSACTION_ALREADY_COMPLETED: 'TRANSACTION_ALREADY_COMPLETED',
  TRANSACTION_ALREADY_CANCELLED: 'TRANSACTION_ALREADY_CANCELLED',
  TRANSACTION_INVALID_STATE: 'TRANSACTION_INVALID_STATE',
  TRANSACTION_DUPLICATE: 'TRANSACTION_DUPLICATE',
  TRANSACTION_IDEMPOTENCY_CONFLICT: 'TRANSACTION_IDEMPOTENCY_CONFLICT',
  TRANSACTION_LIMIT_EXCEEDED: 'TRANSACTION_LIMIT_EXCEEDED',

  /* =========================
     FX / RATES
  ========================== */
  FX_RATE_NOT_FOUND: 'FX_RATE_NOT_FOUND',
  FX_RATE_INVALID: 'FX_RATE_INVALID',
  FX_RATE_EXPIRED: 'FX_RATE_EXPIRED',
  FX_RATE_SYNC_FAILED: 'FX_RATE_SYNC_FAILED',
  FX_PROVIDER_UNAVAILABLE: 'FX_PROVIDER_UNAVAILABLE',
  FX_PROVIDER_TIMEOUT: 'FX_PROVIDER_TIMEOUT',

  /* =========================
     NOTIFICATIONS / OTP
  ========================== */
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ALREADY_USED: 'OTP_ALREADY_USED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_RESEND_LIMIT_REACHED: 'OTP_RESEND_LIMIT_REACHED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',
  NOTIFICATION_QUEUE_ERROR: 'NOTIFICATION_QUEUE_ERROR',

  /* =========================
     RATE LIMITING / SECURITY
  ========================== */
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  IP_BLOCKED: 'IP_BLOCKED',
  DEVICE_BLOCKED: 'DEVICE_BLOCKED',

  /* =========================
     REDIS / CACHE
  ========================== */
  REDIS_CONNECTION_FAILED: 'REDIS_CONNECTION_FAILED',
  REDIS_KEY_NOT_FOUND: 'REDIS_KEY_NOT_FOUND',
  REDIS_WRITE_FAILED: 'REDIS_WRITE_FAILED',
  REDIS_READ_FAILED: 'REDIS_READ_FAILED',

  /* =========================
     QUEUE / JOBS
  ========================== */
  QUEUE_PUBLISH_FAILED: 'QUEUE_PUBLISH_FAILED',
  QUEUE_PROCESSING_FAILED: 'QUEUE_PROCESSING_FAILED',
  JOB_ALREADY_RUNNING: 'JOB_ALREADY_RUNNING',

  /* =========================
     FILE / EXTERNAL SERVICES
  ========================== */
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_UNAUTHORIZED: 'EXTERNAL_SERVICE_UNAUTHORIZED',

  /* =========================
     ANALYTICS
  ========================== */
  ANALYTICS_QUERY_FAILED: 'ANALYTICS_QUERY_FAILED',
  ANALYTICS_DATA_NOT_FOUND: 'ANALYTICS_DATA_NOT_FOUND',

  /* =========================
     PASSWORD / CRYPTO
  ========================== */
  PASSWORD_HASH_FAILED: 'PASSWORD_HASH_FAILED',
  PASSWORD_COMPARE_FAILED: 'PASSWORD_COMPARE_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
